/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainsw;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Luciano Limina
 */
public class AddTipologiaTrenoFrame extends javax.swing.JFrame {
TrainSW trainSW = TrainSW.getIstanza();
Treno treno;
    /**
     * Creates new form addTrenoFrame
     */
    public AddTipologiaTrenoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_idtt = new javax.swing.JTextField();
        txt_nomeTipo = new javax.swing.JTextField();
        txt_num1c = new javax.swing.JTextField();
        txt_posti2c = new javax.swing.JTextField();
        txt_velocita = new javax.swing.JTextField();
        txt_postilet = new javax.swing.JTextField();
        addTipoTreno_button = new javax.swing.JButton();
        annullaTipoTreno_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_prezzo1c = new javax.swing.JTextField();
        prezzo_2c = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Inserisci Tipologia Treno ");

        jLabel2.setText("id tiipologia");

        jLabel3.setText(" nome tipologia");

        jLabel4.setText("numero posti 1c");

        jLabel5.setText("numero posti 2c");

        jLabel6.setText("velocità");

        jLabel7.setText("posti_letto");

        addTipoTreno_button.setText("Avanti");
        addTipoTreno_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTipoTreno_buttonActionPerformed(evt);
            }
        });

        annullaTipoTreno_button.setText("Annulla");
        annullaTipoTreno_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaTipoTreno_buttonActionPerformed(evt);
            }
        });

        jLabel8.setText("prezzo 1C");

        jLabel9.setText("prezzo 2C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_idtt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt_num1c, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_velocita, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(addTipoTreno_button)
                            .addComponent(jLabel8)
                            .addComponent(txt_prezzo1c, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(annullaTipoTreno_button)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(txt_nomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_postilet, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_posti2c, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(prezzo_2c, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomeTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_num1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_posti2c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_velocita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_postilet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_prezzo1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prezzo_2c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTipoTreno_button)
                    .addComponent(annullaTipoTreno_button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTipoTreno_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTipoTreno_buttonActionPerformed
     int id_tt = new Integer(txt_idtt.getText());
     short np1c = new Short(txt_num1c.getText());
     short np2c = new Short(txt_posti2c.getText());
     short post_let = new Short(txt_postilet.getText());
     double velocita = new Double(txt_velocita.getText());
     double prezzo1c = new Double(txt_prezzo1c.getText());
     double prezzo2c = new Double(prezzo_2c.getText());
     
     TipoTreno tt;
     tt  = trainSW.InserisciTipologiaTreno(id_tt, txt_nomeTipo.getText(), post_let, np2c, np1c, velocita, prezzo1c, prezzo2c);
       
       final JFrame confFrame = new JFrame("Visualizza Dati");
      JPanel pan1 = new JPanel(new FlowLayout());
      JButton confButton = new JButton("Conferma");
    JLabel oblab = new JLabel(tt.toString());
        pan1.add(oblab);
      pan1.add(confButton);
      confFrame.add(pan1);
      confFrame.setVisible(true);
      confFrame.setSize(500, 100);        
     
      
      
      confButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                trainSW.confermaTipologiaTreno();
               confFrame.dispose();
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
     
     
        final JFrame gst = new JFrame("Inserisci Treno");
    gst.setVisible(true);
    gst.setSize(100, 200);
    JPanel pan = new JPanel(new FlowLayout());
    pan.setVisible(true);
  
    JLabel insIdT = new JLabel("Inserisci id treno");
    final JTextField txt_idT = new JTextField("             ");
  
    
    final JButton nextAddT = new JButton("Avanti");
    JButton backAddT = new JButton("Annulla");
    

    gst.add(pan);
      pan.add(insIdT);
     pan.add(txt_idT);
     
     pan.add(nextAddT);
     pan.add(backAddT);
  
     nextAddT.addActionListener(new ActionListener() {
     @Override
     public void actionPerformed(ActionEvent e) {
         
         
         gst.dispose();
         
         
         
         
         final JFrame gst3 = new JFrame("Inserisci Treno nel Deposito");
    gst3.setVisible(true);
    gst3.setSize(60, 170);
    JPanel pan3 = new JPanel(new FlowLayout());
    pan3.setVisible(true);
  
    JLabel insIdT = new JLabel("Inserisci id Stazione");
    final JTextField txt_idSt2 = new JTextField(2);
   
  
   
    
    JButton insTDep = new JButton("Fine");
    JButton backAddT = new JButton("Annulla");
    

    gst3.add(pan3);
      pan3.add(insIdT);
     pan3.add(txt_idSt2);
     
     pan3.add(insTDep);
     pan3.add(backAddT);
         
     
     insTDep.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 Integer id_st = new Integer(txt_idSt2.getText());
                 trainSW.InserisciNelDeposito(id_st, treno);
                 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             }
         });
     
     nextAddT.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 Integer id_t = new Integer(txt_idT.getText());
                 
                  treno = trainSW.InserisciTreno(id_t);
                 
                 
                 
                  final JFrame confFrame = new JFrame("Visualizza Dati");
      JPanel pan1 = new JPanel(new FlowLayout());
      JButton confButton = new JButton("Conferma");
    JLabel oblab = new JLabel(treno.toString());
        pan1.add(oblab);
      pan1.add(confButton);
      confFrame.add(pan1);
      confFrame.setVisible(true);
      confFrame.setSize(500, 100);        
     
      
      
      confButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                trainSW.confermaTreno();
               confFrame.dispose();
               
               
               
               
               
               
               
               
               
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
                 
                 //End code here
               
                 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             }
         });
     
     
     
         throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
         
     }
 });
    
     this.dispose();
     
    }//GEN-LAST:event_addTipoTreno_buttonActionPerformed

    private void annullaTipoTreno_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaTipoTreno_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_annullaTipoTreno_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTipologiaTrenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTipologiaTrenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTipologiaTrenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTipologiaTrenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTipologiaTrenoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTipoTreno_button;
    private javax.swing.JButton annullaTipoTreno_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField prezzo_2c;
    private javax.swing.JTextField txt_idtt;
    private javax.swing.JTextField txt_nomeTipo;
    private javax.swing.JTextField txt_num1c;
    private javax.swing.JTextField txt_posti2c;
    private javax.swing.JTextField txt_postilet;
    private javax.swing.JTextField txt_prezzo1c;
    private javax.swing.JTextField txt_velocita;
    // End of variables declaration//GEN-END:variables
}
