package trainsw;
// Generated 18-ago-2017 12.22.10 by Hibernate Tools 4.3.1

import java.util.LinkedList;
import java.util.List;
import org.hibernate.Session;

/**
 * Deposito generated by hbm2java
 */
public class Deposito implements java.io.Serializable {

    private Integer id_dep;
    private Integer id_stazione;
    private Integer numPosti;
    private Stazione stazione;
    private List<Treno> treni;

    public Deposito() {
    }

    public Deposito(Integer id_dep, Integer id_stazione, Integer numPosti) {
        this.id_dep = id_dep;
        this.id_stazione = id_stazione;
        this.numPosti = numPosti;
    }

    public Deposito(Integer id_dep, Integer numPosti) {
        this.id_dep = id_dep;
        this.numPosti = numPosti;
        this.treni=new LinkedList<>();
    }

   

    public Integer getId_dep() {
        return this.id_dep;
    }

    public void setId_dep(Integer id_dep) {
        this.id_dep = id_dep;
    }

    public Integer getId_stazione() {
        return this.id_stazione;
    }

    public void setId_stazione(Integer id_stazione) {
        this.id_stazione = id_stazione;
    }

    public Integer getNumPosti() {
        return this.numPosti;
    }

    public void setNumPosti(Integer numPosti) {
        this.numPosti = numPosti;
    }

    public Stazione getStazione() {
        return stazione;
    }

    public void setStazione(Stazione stazione) {
        this.stazione = stazione;
    }

    public List<Treno> getTreni() {
        return treni;
    }

    public void setTreni(List<Treno> treni) {
        this.treni = treni;
    }

    public void addTrenoDeposito(Treno tr) {
     if(!isFull()){
        treni.add(tr);
     }
    }

    public boolean isFull() {


   
        if (treni.size()< this.numPosti) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Deposito{" + "id_dep=" + id_dep + ", id_stazione=" + id_stazione + ", numPosti=" + numPosti + ", stazione=" + stazione + ", treni=" + treni + '}';
    }

}
